# Group 1: Nature & Wilderness (14 categories)
import os
from .common import (
    expand_file_3levels, expand_file_single,
    DURATIONS_I, DURATIONS_II, DURATIONS_III, DURATIONS_SINGLE,
    NEG_NO_VOCALS_NO_DRUMS, NEG_WITH_CHOIR, NEG_WITH_DRUMS, NEG_FULL_ORCHESTRAL
)

def run_group1(base_dir):
    # 1. Forest
    l1 = [
        ('Ancient sylvan grove ambient (I)', DURATIONS_I[0], NEG_NO_VOCALS_NO_DRUMS,
         'TrackType: Music, instrumental, ancient sylvan grove ambient, peaceful and timeless, gentle wooden flute, soft harp arpeggios, warm string pad, no perceivable tempo, sunbeams piercing giant oak canopy, steady texture with no ending, looping-friendly'),
        ('Mossy stream bank ambient (I)', DURATIONS_I[1], NEG_NO_VOCALS_NO_DRUMS,
         'TrackType: Music, instrumental, mossy stream bank ambient, tranquil and refreshing, delicate hammered dulcimer, soft cello drone, distant birdlike woodwind, 42 BPM, clear water gliding over rounded stones, looping-friendly, steady texture with no ending'),
        ('Pine needle hollow ambient (I)', DURATIONS_I[2], NEG_NO_VOCALS_NO_DRUMS,
         'TrackType: Music, instrumental, pine needle hollow ambient, hushed and secluded, low acoustic guitar harmonics, airy wooden whistle, warm bowed bass, 40 BPM, quiet shaded clearing deep in the evergreen woods, looping-friendly, steady texture with no ending'),
        ('Elder treant sanctuary ambient (I)', DURATIONS_I[3], NEG_NO_VOCALS_NO_DRUMS,
         'TrackType: Music, instrumental, elder treant sanctuary ambient, reverent and grounded, deep contrabass drone, gentle kalimba touches, soft bowed strings, no perceivable tempo, ancient wooden giants resting in silence, steady texture with no ending, looping-friendly'),
        ('Moonlit canopy ambient (I)', DURATIONS_I[4], NEG_NO_VOCALS_NO_DRUMS,
         'TrackType: Music, instrumental, moonlit canopy ambient, serene and silvery, ethereal harp harmonics, soft viola pad, sparse celesta, no perceivable tempo, silver light drifting across tree branches, looping-friendly, steady texture with no ending'),
        ('Wildflower meadow ambient (I)', DURATIONS_I[5], NEG_NO_VOCALS_NO_DRUMS,
         'TrackType: Music, instrumental, wildflower meadow ambient, warm and gentle, fingerpicked acoustic guitar, soft recorder, mellow cello, 45 BPM, bees humming over summer blossoms, looping-friendly, steady texture with no ending'),
        ('Bramble thicket ambient (I)', DURATIONS_I[6], NEG_NO_VOCALS_NO_DRUMS,
         'TrackType: Music, instrumental, bramble thicket ambient, cautious and still, muted pizzicato viola, low wooden flute breaths, dry rustle textures, 38 BPM, watching between tangled thorny branches, steady texture with no ending, looping-friendly'),
        ('Foggy forest dawn ambient (I)', DURATIONS_I[7], NEG_NO_VOCALS_NO_DRUMS,
         'TrackType: Music, instrumental, foggy forest dawn ambient, mystical and cool, glass chimes, soft bass flute, sustained low cellos, no perceivable tempo, white mist curling between elder birch trees, looping-friendly, steady texture with no ending'),
        ('Sun-dappled glade ambient (I)', DURATIONS_I[8], NEG_NO_VOCALS_NO_DRUMS,
         'TrackType: Music, instrumental, sun-dappled glade ambient, soothing and radiant, slow harp glimmers, warm nylon guitar, lush string beds, 44 BPM, leaves stirring in the soft afternoon breeze, steady texture with no ending, looping-friendly'),
        ('Deep briarwood ambient (I)', DURATIONS_I[9], NEG_NO_VOCALS_NO_DRUMS,
         'TrackType: Music, instrumental, deep briarwood ambient, solemn and solitary, bowed acoustic bass, solitary alto flute, muted string swells, no perceivable tempo, paths untrodden for a century, looping-friendly, steady texture with no ending'),
        ('Hidden spring ambient (I)', DURATIONS_I[10], NEG_NO_VOCALS_NO_DRUMS,
         'TrackType: Music, instrumental, hidden spring ambient, crystalline and peaceful, sparse dulcimer notes, light flute flutter, soft pad drone, 46 BPM, bubbling natural font in an overgrown hollow, steady texture with no ending, looping-friendly'),
        ('High canopy wind ambient (I)', DURATIONS_I[11], NEG_NO_VOCALS_NO_DRUMS,
         'TrackType: Music, instrumental, high canopy wind ambient, expansive and airy, sustained upper strings, gentle bamboo flute, low warm drones, no perceivable tempo, looking down upon an endless green sea of treetops, looping-friendly, steady texture with no ending'),
        ('Forest borderland ambient (I)', DURATIONS_I[12], NEG_NO_VOCALS_NO_DRUMS,
         'TrackType: Music, instrumental, forest borderland ambient, open and calm, acoustic guitar strumming gently, warm violin lines, low pads, 48 BPM, where the open pasture meets the ancient tree line, steady texture with no ending, looping-friendly'),
        ('Fallen colossus oak ambient (I)', DURATIONS_I[13], NEG_NO_VOCALS_NO_DRUMS,
         'TrackType: Music, instrumental, fallen colossus oak ambient, solemn and mossy, low cello swells, sparse harp notes, wooden percussive clicks, 40 BPM, a centuries-old trunk blanketed in velvet moss, looping-friendly, steady texture with no ending'),
        ('Secret dryad path ambient (I)', DURATIONS_I[14], NEG_WITH_CHOIR,
         'TrackType: Music, secret dryad path ambient, enchanted and hushed, wordless ethereal choir pad, gentle harp, soft flute breaths, no perceivable tempo, a mossy path guarded by tree spirits, steady texture with no ending, looping-friendly'),
        ('Silverleaf forest ambient (I)', DURATIONS_I[15], NEG_NO_VOCALS_NO_DRUMS,
         'TrackType: Music, instrumental, silverleaf forest ambient, luminous and pure, celesta touches, bowed viola, warm acoustic guitar, 42 BPM, glowing leaves shimmering in twilight, looping-friendly, steady texture with no ending'),
        ('Ancient hunter trail ambient (I)', DURATIONS_I[16], NEG_NO_VOCALS_NO_DRUMS,
         'TrackType: Music, instrumental, ancient hunter trail ambient, watchful and patient, low flute, muted plucked cello, faint drone, 40 BPM, animal tracks leading through quiet undergrowth, steady texture with no ending, looping-friendly'),
        ('Verdant glen ambient (I)', DURATIONS_I[17], NEG_NO_VOCALS_NO_DRUMS,
         'TrackType: Music, instrumental, verdant glen ambient, lush and restful, gentle harp, warm string ensemble, soft wooden whistle, 44 BPM, protected valley teeming with gentle woodland life, looping-friendly, steady texture with no ending'),
        ('Elder canopy twilight ambient (I)', DURATIONS_I[18], NEG_NO_VOCALS_NO_DRUMS,
         'TrackType: Music, instrumental, elder canopy twilight ambient, purple and quiet, warm acoustic bass, soft flute, drifting pad textures, no perceivable tempo, fading daylight filtered through thick green leaves, steady texture with no ending, looping-friendly'),
        ('Sacred grove sanctuary ambient (I)', DURATIONS_I[19], NEG_NO_VOCALS_NO_DRUMS,
         'TrackType: Music, instrumental, sacred grove sanctuary ambient, reverent and pure, slow harp arpeggios, solo cello, glass chimes, 38 BPM, an untamed natural shrine where no axe has ever swung, looping-friendly, steady texture with no ending')
    ]
    l2 = [
        ('Woodland traveler tune (II)', DURATIONS_II[0], NEG_NO_VOCALS_NO_DRUMS,
         'TrackType: Music, instrumental, woodland traveler tune, cheerful and wandering, wooden flute melody, fingerpicked acoustic guitar, soft bodhran pulse, 78 BPM, following a sunlit forest trail, ambling adventure'),
        ('Druid ritual song (II)', DURATIONS_II[1], NEG_NO_VOCALS_NO_DRUMS,
         'TrackType: Music, instrumental, druid ritual song, reverent and organic, nyckelharpa melody, warm cello accompaniment, low frame drum, 72 BPM, seasonal blessing at the standing stones'),
        ('Sylvan stream dance (II)', DURATIONS_II[2], NEG_NO_VOCALS_NO_DRUMS,
         'TrackType: Music, instrumental, sylvan stream dance, lively and graceful, Celtic harp motifs, wooden whistle, pizzicato strings, 84 BPM, water nymphs leaping along the brook'),
        ('Canopy bridge promenade (II)', DURATIONS_II[3], NEG_NO_VOCALS_NO_DRUMS,
         'TrackType: Music, instrumental, canopy bridge promenade, noble and airy, classical acoustic guitar, viola melody, light hand drum, 76 BPM, walking rope bridges suspended between giant redwoods'),
        ('Forest ranger march (II)', DURATIONS_II[4], NEG_WITH_DRUMS,
         'TrackType: Music, instrumental, forest ranger march, vigilant and steady, low horn harmonies, crisp snare cadence, driving acoustic guitar, 82 BPM, patrolling the ancient woodland border'),
        ('Greenwood gathering (II)', DURATIONS_II[5], NEG_NO_VOCALS_NO_DRUMS,
         'TrackType: Music, instrumental, greenwood gathering, festive and warm, fiddle lead, bouzouki chords, wooden flute counterpoint, 80 BPM, forest folk sharing cider under the boughs'),
        ('Mossy ruin wanderer (II)', DURATIONS_II[6], NEG_NO_VOCALS_NO_DRUMS,
         'TrackType: Music, instrumental, mossy ruin wanderer, curious and wondrous, solo cello melody, dulcimer patterns, ambient pads, 68 BPM, exploring an overgrown stone watchtower in the woods'),
        ('Morning mist reel (II)', DURATIONS_II[7], NEG_NO_VOCALS_NO_DRUMS,
         'TrackType: Music, instrumental, morning mist reel, bright and rhythmic, tin whistle, strummed mandolin, acoustic bass, 86 BPM, clearing fog revealing a hidden sylvan valley'),
        ('Dryad blessing (II)', DURATIONS_II[8], NEG_WITH_CHOIR,
         'TrackType: Music, dryad blessing, mystical and melodic, wordless soprano vocalise, gentle harp, soft strings, 70 BPM, spirits of the trees offering guidance to travelers'),
        ('Briarwood gallop (II)', DURATIONS_II[9], NEG_WITH_DRUMS,
         'TrackType: Music, instrumental, briarwood gallop, adventurous and brisk, acoustic guitar strum, agile flute runs, light percussion, 88 BPM, riding ponies through leafy bridleways'),
        ('Sunbeam waltz (II)', DURATIONS_II[10], NEG_NO_VOCALS_NO_DRUMS,
         'TrackType: Music, instrumental, sunbeam waltz, graceful and sweet, harp arpeggios, wooden recorder, warm string ensemble, 74 BPM, golden dust motes dancing in forest light'),
        ('Elder oak hymn (II)', DURATIONS_II[11], NEG_NO_VOCALS_NO_DRUMS,
         'TrackType: Music, instrumental, elder oak hymn, solemn and majestic, French horns, rich cello section, harp glissandi, 66 BPM, standing before the oldest tree in the realm'),
        ('Herbalist journey (II)', DURATIONS_II[12], NEG_NO_VOCALS_NO_DRUMS,
         'TrackType: Music, instrumental, herbalist journey, thoughtful and pastoral, plucked lute, soft oboe melody, gentle viola, 75 BPM, collecting rare moon-lilies along the forest ridge'),
        ('Whispering boughs (II)', DURATIONS_II[13], NEG_NO_VOCALS_NO_DRUMS,
         'TrackType: Music, instrumental, whispering boughs, mysterious and lyrical, bass flute lead, classical guitar, warm ambient swells, 64 BPM, secret messages carried on woodland breezes'),
        ('Hedge witch cottage (II)', DURATIONS_II[14], NEG_NO_VOCALS_NO_DRUMS,
         'TrackType: Music, instrumental, hedge witch cottage, cozy and quirky, pizzicato violin, wooden marimba, dulcimer, 80 BPM, bubbling herb pots and hanging dried roots in a forest hut'),
        ('Autumn canopy drift (II)', DURATIONS_II[15], NEG_NO_VOCALS_NO_DRUMS,
         'TrackType: Music, instrumental, autumn canopy drift, bittersweet and flowing, solo violin, nylon guitar, warm pads, 70 BPM, golden leaves swirling down to the forest floor'),
        ('Sylvan court procession (II)', DURATIONS_II[16], NEG_WITH_CHOIR,
         'TrackType: Music, sylvan court procession, elegant and magical, wordless choir harmonies, Celtic harp, wooden flutes, 76 BPM, noble elves traveling beneath arching green branches'),
        ('Deepwood tracking (II)', DURATIONS_II[17], NEG_WITH_DRUMS,
         'TrackType: Music, instrumental, deepwood tracking, focused and tense, low cello ostinato, muted frame drum, breathy bamboo flute, 72 BPM, following fresh monster prints through the brush'),
        ('Firefly meadow folk (II)', DURATIONS_II[18], NEG_NO_VOCALS_NO_DRUMS,
         'TrackType: Music, instrumental, firefly meadow folk, dreamy and rhythmic, glockenspiel glints, acoustic guitar, soft violin, 78 BPM, thousands of glowing insects lighting the forest edge'),
        ('Ancient boundary stone (II)', DURATIONS_II[19], NEG_NO_VOCALS_NO_DRUMS,
         'TrackType: Music, instrumental, ancient boundary stone, majestic and watchful, French horn solo, warm string bed, harp, 68 BPM, passing the carved boundary marking fairy territory')
    ]
    l3 = [
        ('Wrath of the forest (III)', DURATIONS_III[0], NEG_FULL_ORCHESTRAL,
         'TrackType: Music, wrath of the forest, furious and epic, thundering taiko drums, roaring brass, racing staccato strings, wordless choir, 115 BPM, the ancient trees waking to defend their heartland'),
        ('Druid circle tempest (III)', DURATIONS_III[1], NEG_FULL_ORCHESTRAL,
         'TrackType: Music, druid circle tempest, driving and mystical, massed bodhran drums, soaring nyckelharpa, screaming high strings, 120 BPM, channeling lightning through the standing stones'),
        ('Stampede of the wild herd (III)', DURATIONS_III[2], NEG_FULL_ORCHESTRAL,
         'TrackType: Music, instrumental, stampede of the wild herd, intense and unstoppable, heavy pounding percussion, blazing French horns, surging cellos, 128 BPM, hundreds of enchanted stags crashing through the brush'),
        ('Sylvan guardian awakening (III)', DURATIONS_III[3], NEG_FULL_ORCHESTRAL,
         'TrackType: Music, instrumental, sylvan guardian awakening, grand and titanic, booming orchestral drums, heroic horn fanfare, climbing strings, 110 BPM, a colossal forest colossus rising to battle'),
        ('High canopy chase (III)', DURATIONS_III[4], NEG_FULL_ORCHESTRAL,
         'TrackType: Music, instrumental, high canopy chase, breathless and thrilling, rapid pizzicato runs, pounding frame drums, agile woodwind shrieks, 132 BPM, leaping between swaying rope bridges high in the trees'),
        ('Wild hunt of the greenwood (III)', DURATIONS_III[5], NEG_FULL_ORCHESTRAL,
         'TrackType: Music, wild hunt of the greenwood, frenzied and mythical, driving war horns, galloping percussion, soaring wordless choir, 126 BPM, spectral riders sweeping across the moonlit treetops'),
        ('Ancient treant march (III)', DURATIONS_III[6], NEG_FULL_ORCHESTRAL,
         'TrackType: Music, instrumental, ancient treant march, heavy and monolithic, earth-shaking low brass, massive drum impacts, grinding low strings, 96 BPM, giant walking trees marching upon enemy siege engines'),
        ('Blaze in the canopy (III)', DURATIONS_III[7], NEG_FULL_ORCHESTRAL,
         'TrackType: Music, instrumental, blaze in the canopy, desperate and heroic, galloping strings, screaming brass fanfares, urgent timpani rolls, 130 BPM, racing to stop a magical wildfire consuming the sacred forest'),
        ('Avatar of the green God (III)', DURATIONS_III[8], NEG_FULL_ORCHESTRAL,
         'TrackType: Music, avatar of the green God, transcendent and colossal, majestic brass chorale, full orchestral swells, thunderous percussion, wordless choir crescendo, 104 BPM, nature itself appearing in monumental glory'),
        ('Briar storm breach (III)', DURATIONS_III[9], NEG_FULL_ORCHESTRAL,
         'TrackType: Music, instrumental, briar storm breach, ferocious and relentless, razor-sharp string runs, heavy war drums, biting brass stabs, 122 BPM, supernatural thorn vines tearing apart invading fortress gates'),
        ('Emerald dragon flight (III)', DURATIONS_III[10], NEG_FULL_ORCHESTRAL,
         'TrackType: Music, emerald dragon flight, magnificent and grand, sweeping full orchestra, soaring French horns, rolling timpani, choral accents, 112 BPM, a great forest dragon taking flight over the canopy'),
        ('Sylvan rebellion (III)', DURATIONS_III[11], NEG_FULL_ORCHESTRAL,
         'TrackType: Music, sylvan rebellion, inspiring and fast, Celtic fiddle duel with full orchestra, driving drums, triumphant choir, 124 BPM, woodland creatures and elven warriors breaking the siege'),
        ('Heart of the elder wood (III)', DURATIONS_III[12], NEG_FULL_ORCHESTRAL,
         'TrackType: Music, heart of the elder wood, awe-inspiring and overwhelming, colossal orchestral crescendo, radiant brass, thundering timpani, 100 BPM, standing before the fountain of life at the forest center'),
        ('Forest beast duel (III)', DURATIONS_III[13], NEG_FULL_ORCHESTRAL,
         'TrackType: Music, instrumental, forest beast duel, vicious and primal, aggressive cello ostinato, heavy war drums, screeching woodwinds, 118 BPM, two gigantic woodland apex predators clashing in the glade'),
        ('Moonlit grove ascension (III)', DURATIONS_III[14], NEG_FULL_ORCHESTRAL,
         'TrackType: Music, moonlit grove ascension, radiant and triumphant, shimmering high strings, triumphant brass fanfares, soaring wordless choir, 106 BPM, ancient druidic magic reaching its glorious peak'),
        ('Ranger last charge (III)', DURATIONS_III[15], NEG_FULL_ORCHESTRAL,
         'TrackType: Music, ranger last charge, brave and relentless, driving military snares, soaring trumpet melody, heroic strings, 120 BPM, a band of elite bowmen charging to save their woodland homeland'),
        ('Overgrowth cataclysm (III)', DURATIONS_III[16], NEG_FULL_ORCHESTRAL,
         'TrackType: Music, overgrowth cataclysm, wild and destructive, rapid chaotic string arpeggios, massive taiko strikes, brass blasts, 128 BPM, unstoppable magical roots swallowing an entire castle'),
        ('Fey king battle anthem (III)', DURATIONS_III[17], NEG_FULL_ORCHESTRAL,
         'TrackType: Music, fey king battle anthem, magnificent and wild, blistering fiddle lead, epic orchestral percussion, soaring choir, 125 BPM, the monarch of the woods unleashing untamed fairy magic'),
        ('Elder dryad sacrifice (III)', DURATIONS_III[18], NEG_FULL_ORCHESTRAL,
         'TrackType: Music, elder dryad sacrifice, tragic and towering, weeping solo cello rising into massive tutti orchestra, sorrowful wordless choir, 98 BPM, giving up ancient life to restore the scorched woods'),
        ('Triumphant green dawn (III)', DURATIONS_III[19], NEG_FULL_ORCHESTRAL,
         'TrackType: Music, triumphant green dawn, victorious and radiant, blazing brass fanfare, full string orchestra, crashing cymbals, majestic choir, 108 BPM, sunrise illuminating the healed and victorious woodland realm')
    ]
    expand_file_3levels(os.path.join(base_dir, 'forest.md'), l1, l2, l3)
    print('Finished Group 1 test (forest.md)')

if __name__ == '__main__':
    run_group1('prompts/ambience')
