# Batch 1: Categories 1 to 15
import os
from .engine import (
    apply_expansion_3levels, apply_expansion_single,
    DUR_I, DUR_II, DUR_III, DUR_SINGLE,
    NEG_DRY, NEG_CHOIR, NEG_DRUMS, NEG_FULL
)

def run(base_dir):
    # 1. ancient-discovery
    l1 = [
        ('Sumerian vault ambient (I)', DUR_I[0], NEG_DRY, 'TrackType: Music, instrumental, ancient ambient, solemn and hollow, low duduk drone, bowed double bass, sparse chime resonance, no perceivable tempo, gold artifacts untouched for three thousand years, steady texture with no ending, looping-friendly'),
        ('Forgotten obelisk ambient (I)', DUR_I[1], NEG_DRY, 'TrackType: Music, instrumental, timeworn ambient, reverent awe, deep cello pad, soft harp harmonics, distant stone reverb, 40 BPM, weathered hieroglyphs glowing in the dark, looping-friendly, steady texture with no ending'),
        ('Sunken archives ambient (I)', DUR_I[2], NEG_DRY, 'TrackType: Music, instrumental, ancient drone ambient, quiet mystery, bowed dulcimer, low bass flute swells, glass harmonics, no perceivable tempo, thousands of clay tablets submerged in dust, steady texture with no ending, looping-friendly'),
        ('Precursor tomb ambient (I)', DUR_I[3], NEG_DRY, 'TrackType: Music, instrumental, meditative ancient ambient, hushed wonder, slow string pad, solitary duduk melody, warm contrabass, 42 BPM, standing before the sarcophagus of the first emperor, looping-friendly, steady texture with no ending'),
        ('Buried colossus feet ambient (I)', DUR_I[4], NEG_DRY, 'TrackType: Music, instrumental, ruins ambient, vast and humbling, deep granite drones, sparse harp glints, low horn long tones, no perceivable tempo, monumental stone toes carved into mountain roots, steady texture with no ending, looping-friendly'),
        ('Starlight chamber ambient (I)', DUR_I[5], NEG_DRY, 'TrackType: Music, instrumental, ancient temple ambient, celestial and ancient, celesta sparkles, soft cello drone, airy wooden flute, 45 BPM, astrological ceiling reflecting forgotten constellations, looping-friendly, steady texture with no ending'),
        ('Fossilized sanctum ambient (I)', DURATIONS_I := DUR_I[6], NEG_DRY, 'TrackType: Music, instrumental, desert ruins ambient, dry and timeless, airy bamboo flute, sustained cellos, soft chime touches, no perceivable tempo, petrified trees standing inside a buried courtyard, steady texture with no ending, looping-friendly'),
        ('Elder rune threshold ambient (I)', DUR_I[7], NEG_DRY, 'TrackType: Music, instrumental, sunken library ambient, dark curiosity, muted harp, low duduk breaths, tremolo string drone, 40 BPM, carved warning runes glowing faintly in cold air, looping-friendly, steady texture with no ending'),
        ('Cyclopean hallway ambient (I)', DUR_I[8], NEG_DRY, 'TrackType: Music, instrumental, megalith ambient, cold gravity, sub-bass string swells, bowed metal textures, solitary harp notes, 38 BPM, corridor built for giants a hundred feet high, steady texture with no ending, looping-friendly'),
        ('Lost dynastic crypt ambient (I)', DUR_I[9], NEG_DRY, 'TrackType: Music, instrumental, dwarven gate ambient, grave and monumental, heavy bass drone, low horn chords, hammered dulcimer taps, no perceivable tempo, tomb doors sealed with adamantine locks, looping-friendly, steady texture with no ending'),
        ('Eldritch fresco ambient (I)', DUR_I[10], NEG_DRY, 'TrackType: Music, instrumental, ancient ambient, eerie reverence, glass harmonica drone, bowed cello, soft waterphone, 44 BPM, ceiling frescoes depicting pre-human deities, steady texture with no ending, looping-friendly'),
        ('Astral observatory ambient (I)', DUR_I[11], NEG_DRY, 'TrackType: Music, instrumental, timeworn ambient, mystical stillness, high string shimmer, gentle harp patterns, low viola, no perceivable tempo, bronze astrolabes aligning by forgotten clockwork, looping-friendly, steady texture with no ending'),
        ('Chamber of the first king ambient (I)', DUR_I[12], NEG_DRY, 'TrackType: Music, instrumental, ancient drone ambient, regal and quiet, warm cello swells, distant brass pad, slow dulcimer, 40 BPM, throne carved directly from emerald crystal, steady texture with no ending, looping-friendly'),
        ('Sealed reliquary ambient (I)', DUR_I[13], NEG_DRY, 'TrackType: Music, instrumental, ruins ambient, breath held, soft tremolo strings, lone duduk, delicate chime, no perceivable tempo, golden reliquary resting upon an altar of black stone, looping-friendly, steady texture with no ending'),
        ('Underground ziggurat stairs ambient (I)', DUR_I[14], NEG_DRY, 'TrackType: Music, instrumental, ancient temple ambient, descending awe, low contrabass, airy flute breaths, stone echo textures, 42 BPM, ten thousand steps spiraling into the deep earth, steady texture with no ending, looping-friendly'),
        ('Sunken throne room ambient (I)', DUR_I[15], NEG_DRY, 'TrackType: Music, instrumental, desert ruins ambient, majestic stillness, warm string pad, solo cello, sparse harp plucks, no perceivable tempo, dunes spilling over ivory thrones, looping-friendly, steady texture with no ending'),
        ('Ancient mechanism sleep ambient (I)', DUR_I[16], NEG_DRY, 'TrackType: Music, instrumental, megalith ambient, dormant power, deep resonant drones, soft glass taps, muted brass swells, 38 BPM, gigantic cogwheels asleep in subterranean darkness, steady texture with no ending, looping-friendly'),
        ('Elder wisdom chamber ambient (I)', DUR_I[17], NEG_CHOIR, 'TrackType: Music, ancient library ambient, enlightened calm, wordless choral pad, gentle harp, soft viola, 44 BPM, glowing crystalline scrolls floating in silence, looping-friendly, steady texture with no ending'),
        ('Pillar of eternity ambient (I)', DUR_I[18], NEG_DRY, 'TrackType: Music, instrumental, ancient ambient, infinite stillness, sustained bass drone, solitary bamboo flute, warm strings, no perceivable tempo, a single monolith holding up the cavern ceiling, steady texture with no ending, looping-friendly'),
        ('First civilization dawn ambient (I)', DUR_I[19], NEG_DRY, 'TrackType: Music, instrumental, ruins ambient, profound awe, cello ensemble, duduk phrases, shimmering celesta, 45 BPM, first light touching carvings older than history, looping-friendly, steady texture with no ending')
    ]
    l2 = [
        ('Archaeologist revelation (II)', DUR_II[0], NEG_DRY, 'TrackType: Music, instrumental, cinematic ancient wonder, curious and inspired, solo cello melody, duduk accompaniment, harp arpeggios, 72 BPM, brushing centuries of dust off a bronze map tablet'),
        ('Stepping into the ruins (II)', DUR_II[1], NEG_DRY, 'TrackType: Music, instrumental, ancient chamber piece, cautious awe, plucked oud, warm viola lines, soft dulcimer, 68 BPM, first torchlight crossing the threshold of a forgotten palace'),
        ('Decoding elder script (II)', DUR_II[2], NEG_DRY, 'TrackType: Music, instrumental, mystic ancient orchestral, thoughtful and searching, duduk lead, gentle string swells, celesta accents, 75 BPM, translating the glyphs that open the inner gate'),
        ('Ziggurat terrace walk (II)', DUR_II[3], NEG_DRY, 'TrackType: Music, instrumental, lost temple orchestral, expansive wonder, cello section, airy flute, warm harp, 70 BPM, walking along elevated stone battlements above the sands'),
        ('Whispers of the ancients (II)', DUR_II[4], NEG_CHOIR, 'TrackType: Music, ancient wonder theme, ethereal and reverent, wordless soprano melody, soft strings, distant chimes, 66 BPM, echoes of long-dead priests lingering in the stone alcoves'),
        ('Golden idol chamber (II)', DUR_II[5], NEG_DRY, 'TrackType: Music, instrumental, ruined city orchestral, dazzling awe, harp glissandi, French horn chords, soaring cello, 74 BPM, torchlight catching the massive golden face of an ancient god'),
        ('Hall of ten thousand kings (II)', DUR_II[6], NEG_DRY, 'TrackType: Music, instrumental, sacred vault orchestral, solemn grandeur, low string ostinato, English horn, plucked dulcimer, 76 BPM, marching past endless rows of carved statues'),
        ('Elder astrology puzzle (II)', DUR_II[7], NEG_DRY, 'TrackType: Music, instrumental, antiquity chamber ambient, clever and mysterious, marimba touches, pizzicato strings, bamboo flute, 78 BPM, turning heavy stone dials to align the planet symbols'),
        ('Subterranean river of the ancients (II)', DUR_II[8], NEG_DRY, 'TrackType: Music, instrumental, elder ruins orchestral, flowing and vast, cello melody, acoustic guitar arpeggios, ambient string bed, 70 BPM, boats drifting into the buried port of the first empire'),
        ('Titan sarcophagus approach (II)', DUR_II[9], NEG_DRY, 'TrackType: Music, instrumental, buried colossus orchestral, heavy curiosity, low horn swells, tremolo violas, slow harp, 64 BPM, approaching the resting place of a giant ruler'),
        ('Murals of the first war (II)', DUR_II[10], NEG_DRUMS, 'TrackType: Music, instrumental, ancient chamber piece, historic gravity, frame drum pulse, low brass, solemn strings, 72 BPM, studying carved depictions of the battle between gods and primordials'),
        ('Sunken courtyard exploration (II)', DUR_II[11], NEG_DRY, 'TrackType: Music, instrumental, lost temple orchestral, sunlit mystery, flute melody, acoustic bass, warm pads, 75 BPM, finding rare flowers growing in ancient palace rubble'),
        ('Unlocking the chronometer (II)', DUR_II[12], NEG_DRY, 'TrackType: Music, instrumental, cinematic ancient wonder, intricate motion, celesta, pizzicato cello, duduk, 80 BPM, gears turning inside an ancient bronze device'),
        ('The elder vault unlocks (II)', DUR_II[13], NEG_DRY, 'TrackType: Music, instrumental, sacred vault orchestral, rising anticipation, swelling strings, noble French horns, harp, 76 BPM, heavy stone counterweights sinking into the floor'),
        ('Passage of the guardians (II)', DUR_II[14], NEG_DRY, 'TrackType: Music, instrumental, antiquity chamber ambient, alert reverence, viola solo, bass flute, quiet dulcimer rolls, 68 BPM, walking between dormant stone sentinel statues'),
        ('Sanctum of the forgotten stars (II)', DUR_II[15], NEG_CHOIR, 'TrackType: Music, mystic ancient orchestral, luminous and awe-inspiring, wordless choral pads, shimmering strings, harp, 70 BPM, looking up at a crystal ceiling projecting astral light'),
        ('Caravan at the pyramid gates (II)', DUR_II[16], NEG_DRUMS, 'TrackType: Music, instrumental, ruined city orchestral, exotic and bold, oud, frame drum rhythm, cello ensemble, 78 BPM, camels and explorers arriving at the monumental entry gate'),
        ('Scroll keeper study (II)', DUR_II[17], NEG_DRY, 'TrackType: Music, instrumental, ancient discovery theme, serene and scholarly, solo cello, nylon guitar, soft strings, 66 BPM, reading preserved papyrus scrolls by candlelight'),
        ('Ascending the altar steps (II)', DUR_II[18], NEG_DRY, 'TrackType: Music, instrumental, elder ruins orchestral, climbing wonder, rising string progression, noble horns, harp, 74 BPM, reaching the pinnacle of the ancient ceremonial mound'),
        ('Breath of the first kingdom (II)', DUR_II[19], NEG_DRY, 'TrackType: Music, instrumental, cinematic ancient wonder, majestic resolve, full string orchestra, duduk, English horn, 72 BPM, looking out over the uncovered expanse of the lost civilization')
    ]
    l3 = [
        ('Awakening of the ancient titan (III)', DUR_III[0], NEG_FULL, 'TrackType: Music, epic orchestral discovery, colossal and overwhelming, thundering taiko drums, roaring brass fanfares, surging strings, wordless choir, 110 BPM, the mountain-sized statue grinding to life and opening glowing eyes'),
        ('Sunrise on the lost empire (III)', DUR_III[1], NEG_FULL, 'TrackType: Music, instrumental, monumental orchestral reveal, glorious majesty, soaring French horns, sweeping strings, rolling timpani, harp cascades, 105 BPM, golden dawn rays illuminating the entire buried city'),
        ('The ancient engine starts (III)', DUR_III[2], NEG_FULL, 'TrackType: Music, ancient awakening orchestral, earth-shaking and thunderous, low brass blasts, driving percussion, screaming violins, choir crescendo, 120 BPM, subterranean dynastic power grid firing up after millennia'),
        ('Ascension of the elder god (III)', DUR_III[3], NEG_FULL, 'TrackType: Music, epic temple orchestral, radiant and terrifying, massive brass chorale, thundering drums, soaring wordless soprano and choir, 100 BPM, divine ancient presence filling the sanctum'),
        ('Collapse of the ziggurat (III)', DUR_III[4], NEG_FULL, 'TrackType: Music, instrumental, lost civilization finale, urgent and catastrophic, furious percussion, blaring horns, frantic string arpeggios, 130 BPM, racing down crumbling megalith steps as the temple collapses'),
        ('Unveiling the eternal crown (III)', DUR_III[5], NEG_FULL, 'TrackType: Music, relic revelation orchestral, ecstatic grandeur, soaring trumpet fanfares, full orchestra, crashing cymbals, triumphant choir, 108 BPM, lifting the artifact of creation into the sky'),
        ('Battle for the ancient gate (III)', DUR_III[6], NEG_FULL, 'TrackType: Music, instrumental, elder gate orchestral, heroic and relentless, heavy war drums, driving cello ostinatos, noble brass themes, 122 BPM, defending the entrance to the ancient realm against invaders'),
        ('Observatory aligns with the cosmos (III)', DUR_III[7], NEG_FULL, 'TrackType: Music, ancient stars orchestral, majestic and cosmic, shimmering high violins, massive brass swells, thunderous timpani, choir, 104 BPM, cosmic beam of light shooting from the pyramid into the galaxy'),
        ('Tomb guardian onslaught (III)', DUR_III[8], NEG_FULL_ORCHESTRAL := NEG_FULL, 'TrackType: Music, instrumental, colossus orchestral, ferocious and massive, pounding taiko, shrieking brass, aggressive low strings, 126 BPM, four giant stone colossi attacking simultaneously'),
        ('The lost dynasty returns (III)', DUR_III[9], NEG_FULL, 'TrackType: Music, monumental orchestral reveal, triumphant and immortal, full brass choir, sweeping string section, rolling drums, majestic choir, 106 BPM, spirits of the ancient army appearing in golden armor'),
        ('Rays of the sun king (III)', DUR_III[10], NEG_FULL, 'TrackType: Music, epic temple orchestral, blinding brilliance, blazing trumpet fanfares, full strings, soaring choir, crashing cymbals, 112 BPM, solar energy charging the obelisk of light'),
        ('Escape from the crumbling crypt (III)', DUR_III[11], NEG_FULL, 'TrackType: Music, instrumental, ziggurat ascent orchestral, breathless momentum, racing strings, pounding percussion, screaming horns, 134 BPM, dodging falling stone pillars while riding out of the ruins'),
        ('Secret of the primeval architects (III)', DUR_III[12], NEG_FULL, 'TrackType: Music, epic orchestral discovery, profound revelation, towering brass chords, full orchestra swells, glorious choir, 98 BPM, understanding the ultimate truth of how the world was built'),
        ('Wrath of the mummy king (III)', DUR_III[13], NEG_FULL, 'TrackType: Music, ancient awakening orchestral, terrifying and dark, dissonant brass roars, heavy war drums, screaming choir, 118 BPM, the undead pharaoh unleashing divine locust swarms'),
        ('Chamber of eternity unlocks (III)', DUR_III[14], NEG_FULL, 'TrackType: Music, instrumental, relic revelation orchestral, radiant triumph, sweeping harp glissandi, soaring horns, majestic strings, 102 BPM, the final adamantine door opening to reveal the well of immortality'),
        ('Titan army awakens (III)', DUR_III[15], NEG_FULL, 'TrackType: Music, elder gate orchestral, monumental and unstoppable, earth-shaking bass drums, blaring brass section, surging strings, 114 BPM, thousands of stone soldiers marching out of cavern walls'),
        ('Star-forged blade revealed (III)', DUR_III[16], NEG_FULL, 'TrackType: Music, instrumental, epic temple orchestral, awe-inspiring power, French horn solo rising to full brass, timpani rolls, choir, 108 BPM, pulling the legendary sword from the ancient altar'),
        ('Sands swallow the ruins (III)', DUR_III[17], NEG_FULL, 'TrackType: Music, lost civilization finale, tragic and grand, weeping strings building into massive orchestral wave, solemn choir, 100 BPM, the desert taking back the uncovered empire for eternity'),
        ('First king triumphant march (III)', DUR_III[18], NEG_FULL, 'TrackType: Music, instrumental, ziggurat ascent orchestral, noble and mighty, military snare rolls, glorious brass fanfares, driving strings, 116 BPM, victorious procession through the monumental stone arches'),
        ('Legacy of the ancients (III)', DUR_III[19], NEG_FULL, 'TrackType: Music, epic orchestral discovery, timeless and exalted, full orchestra crescendo, soaring wordless choir, crashing cymbals, 104 BPM, immortal fantasy anthem celebrating the wonder of the forgotten world')
    ]
    apply_expansion_3levels(os.path.join(base_dir, 'ancient-discovery.md'), l1, l2, l3)

    print('Expanded ancient-discovery.md')

if __name__ == '__main__':
    run('prompts/ambience')
