# Batch 1 Complete (Files 1 to 15)
import os
from builders.engine import (
    apply_expansion_3levels, apply_expansion_single,
    DUR_I, DUR_II, DUR_III, DUR_SINGLE,
    NEG_DRY, NEG_CHOIR, NEG_DRUMS, NEG_FULL
)

def run_batch1(base_dir):
    # 2. aqua
    l1_aqua = [
        ('Kelp forest drift ambient (I)', DUR_I[0], NEG_DRY, 'TrackType: Music, instrumental, underwater ambient, weightless and green, bowed glass harmonica, soft waterphone, deep sub bass, no perceivable tempo, sunlight filtering through towering kelp fronds, steady texture with no ending, looping-friendly'),
        ('Sunken reef ambient (I)', DUR_I[1], NEG_DRY, 'TrackType: Music, instrumental, coral reef ambient, peaceful and luminous, gentle harp harmonics, airy wooden flute, warm string pad, 40 BPM, colorful fish darting through submerged coral arches, looping-friendly, steady texture with no ending'),
        ('Abyssal trench ambient (I)', DUR_I[2], NEG_DRY, 'TrackType: Music, instrumental, deep ocean ambient, dark and vast, sub-bass drone, eerie bowed cymbals, sparse celesta, no perceivable tempo, miles of black water where bioluminescent creatures glow, steady texture with no ending, looping-friendly'),
        ('Merfolk sanctum ambient (I)', DUR_I[3], NEG_CHOIR, 'TrackType: Music, merfolk ambient, enchanting and calm, wordless ethereal soprano pad, soft Celtic harp, gentle cello, 42 BPM, pearl-encrusted caves beneath the ocean floor, looping-friendly, steady texture with no ending'),
        ('Drowned temple atrium ambient (I)', DUR_I[4], NEG_DRY, 'TrackType: Music, instrumental, sunken ruins ambient, solemn and hollow, water-drip textures, low cello drone, sparse dulcimer, no perceivable tempo, ancient stone pillars submerged under turquoise waves, steady texture with no ending, looping-friendly'),
        ('Bioluminescent cave ambient (I)', DUR_I[5], NEG_DRY, 'TrackType: Music, instrumental, glowing grotto ambient, mysterious and serene, glass bells, warm ambient synth drone, gentle viola, 38 BPM, azure glowing anemones illuminating underwater grottos, looping-friendly, steady texture with no ending'),
        ('Glacial iceberg drift ambient (I)', DUR_I[6], NEG_DRY, 'TrackType: Music, instrumental, arctic sea ambient, cold and crystalline, high bowed metal harmonics, sustained double bass, slow harp, no perceivable tempo, towering blue icebergs floating in freezing waters, steady texture with no ending, looping-friendly'),
        ('Seabed nautilus ambient (I)', DUR_I[7], NEG_DRY, 'TrackType: Music, instrumental, ocean floor ambient, tranquil and ancient, slow marimba tones, cello long notes, soft pad, 44 BPM, ancient spiral shells resting in white sand, looping-friendly, steady texture with no ending'),
        ('Hydrothermal vent ambient (I)', DUR_I[8], NEG_DRY, 'TrackType: Music, instrumental, volcanic sea ambient, warm and bubbling, low brass drone, gentle waterphone textures, muted string swells, 40 BPM, mineral chimneys releasing warm water into cold depths, steady texture with no ending, looping-friendly'),
        ('Sunken galleon graveyard ambient (I)', DUR_I[9], NEG_DRY, 'TrackType: Music, instrumental, shipwreck ambient, haunting stillness, creaking wood textures, solo cello, sparse harp plucks, no perceivable tempo, rotten ship hulls encrusted with barnacles, looping-friendly, steady texture with no ending'),
        ('Whale song hollow ambient (I)', DUR_I[10], NEG_DRY, 'TrackType: Music, instrumental, pelagic ambient, majestic and expansive, bowed contrabass, airy flute swells, deep warm pad, no perceivable tempo, distant leviathans calling across vast ocean depths, steady texture with no ending, looping-friendly'),
        ('Pearl oyster bed ambient (I)', DUR_I[11], NEG_DRY, 'TrackType: Music, instrumental, lagoon ambient, shimmering and gentle, celesta glints, soft acoustic guitar, warm viola, 45 BPM, crystal clear shallow lagoon with glowing pearls, looping-friendly, steady texture with no ending'),
        ('Submerged cavern spring ambient (I)', DUR_I[12], NEG_DRY, 'TrackType: Music, instrumental, underground sea ambient, hushed and pure, delicate dulcimer, soft cello drone, distant water drips, 40 BPM, freshwater welling up in a hidden ocean cave, steady texture with no ending, looping-friendly'),
        ('Siren reef ambient (I)', DUR_I[13], NEG_CHOIR, 'TrackType: Music, siren reef ambient, mesmerizing and perilous, wordless choral hum, gentle harp arpeggios, warm string swells, no perceivable tempo, jagged rocks veiled in sea foam under moonlight, looping-friendly, steady texture with no ending'),
        ('Sunken palace terrace ambient (I)', DUR_I[14], NEG_DRY, 'TrackType: Music, instrumental, aquatic kingdom ambient, regal and quiet, muted French horn pads, harp glimmers, low strings, 42 BPM, marble courtyards claimed by sea anemones, steady texture with no ending, looping-friendly'),
        ('Pelagic drift ambient (I)', DUR_I[15], NEG_DRY, 'TrackType: Music, instrumental, open ocean ambient, boundless calm, high string shimmer, deep sub drone, gentle woodwind, no perceivable tempo, floating peacefully on endless rolling swells, looping-friendly, steady texture with no ending'),
        ('Thermal current ambient (I)', DUR_I[16], NEG_DRY, 'TrackType: Music, instrumental, warm current ambient, soothing and gliding, soft cello ensemble, airy pan flute, warm synth bed, 46 BPM, gliding effortlessly on warm underwater rivers, steady texture with no ending, looping-friendly'),
        ('Forgotten sea god shrine ambient (I)', DUR_I[17], NEG_DRY, 'TrackType: Music, instrumental, oceanic shrine ambient, reverent and ancient, deep brass drone, glass harmonica, sparse harp, no perceivable tempo, stone trident idol covered in golden sea kelp, looping-friendly, steady texture with no ending'),
        ('Jellyfish bloom ambient (I)', DUR_I[18], NEG_DRY, 'TrackType: Music, instrumental, jellyfish grotto ambient, dreamlike and luminous, celesta glints, high string harmonics, warm bass pad, 38 BPM, thousands of glowing bells pulsing through dark waters, steady texture with no ending, looping-friendly'),
        ('Sunken continent shelf ambient (I)', DUR_I[19], NEG_DRY, 'TrackType: Music, instrumental, drowned world ambient, vast and awe-struck, sustained cellos and basses, soft wooden flute, glass chimes, 40 BPM, standing at the edge of a submerged continental drop-off, steady texture with no ending, looping-friendly')
    ]
    l2_aqua = [
        ('Dolphin pod voyage (II)', DUR_II[0], NEG_DRY, 'TrackType: Music, instrumental, oceanic travel tune, joyful and fluid, Celtic harp, wooden flute melody, light marimba, 80 BPM, swimming alongside playful dolphins across sunlit waters'),
        ('Merfolk village celebration (II)', DUR_II[1], NEG_DRUMS, 'TrackType: Music, instrumental, merfolk folk dance, festive and graceful, steel drum touches, accordion, acoustic guitar, frame drum, 84 BPM, gathering for the coral harvest festival'),
        ('Exploring the coral labyrinth (II)', DUR_II[2], NEG_DRY, 'TrackType: Music, instrumental, reef orchestral, curious and bright, pizzicato strings, solo oboe, sparkling harp, 76 BPM, navigating intricate colorful coral passages'),
        ('Sunken galleon treasure search (II)', DUR_II[3], NEG_DRY, 'TrackType: Music, instrumental, underwater mystery theme, cautious wonder, cello melody, acoustic bass, glass harmonica, 70 BPM, opening barnacle-crusted chests inside a wrecked ship'),
        ('Riding the sea turtles (II)', DUR_II[4], NEG_DRY, 'TrackType: Music, instrumental, ocean wanderer orchestral, relaxed and noble, French horn melody, warm string section, harp arpeggios, 68 BPM, gliding calmly on the backs of giant ancient sea turtles'),
        ('Siren cove melody (II)', DUR_II[5], NEG_CHOIR, 'TrackType: Music, siren song orchestral, alluring and bittersweet, wordless soprano lead, solo cello, shimmering harp, 72 BPM, enchanting melody floating over rocky ocean coves'),
        ('Underwater ruins expedition (II)', DUR_II[6], NEG_DRY, 'TrackType: Music, instrumental, submerged city orchestral, historical awe, English horn, plucked dulcimer, warm strings, 74 BPM, mapping submerged streets and marble colonnades'),
        ('Deep sea sub navigation (II)', DUR_II[7], NEG_DRY, 'TrackType: Music, instrumental, aquatic mechanism piece, rhythmic and focused, marimba ostinato, pizzicato violins, bass clarinet, 78 BPM, piloting a brass bathysphere through underwater caverns'),
        ('Tide pool waltz (II)', DUR_II[8], NEG_DRY, 'TrackType: Music, instrumental, seaside chamber waltz, lighthearted and sweet, classical guitar, flute, viola, 82 BPM, tiny sea creatures dancing in crystal clear rock pools'),
        ('Kraken territory scout (II)', DUR_II[9], NEG_DRY, 'TrackType: Music, instrumental, oceanic suspense orchestral, tense and watchful, low contrabass pulse, muted horns, dark string swells, 66 BPM, scanning deep water for giant shadowy tentacles'),
        ('Lagoon sunset sail (II)', DUR_II[10], NEG_DRY, 'TrackType: Music, instrumental, tropical water folk, tranquil and romantic, nylon guitar, solo violin, soft accordion, 70 BPM, drifting into a quiet turquoise bay as dusk falls'),
        ('Pearl diver rhythm (II)', DUR_II[11], NEG_DRUMS, 'TrackType: Music, instrumental, coastal diver rhythm, energetic and rhythmic, wooden xylophone, hand drums, acoustic bass, flute, 86 BPM, diving deep for prized black pearls'),
        ('Water nymph dance (II)', DUR_II[12], NEG_DRY, 'TrackType: Music, instrumental, sylvan water piece, playful and sparkling, harp arpeggios, tin whistle, pizzicato strings, 84 BPM, nymphs splashing in a hidden ocean cavern pool'),
        ('Submerged library deciphering (II)', DUR_II[13], NEG_DRY, 'TrackType: Music, instrumental, ancient oceanic orchestral, scholarly wonder, cello section, glass bells, soft woodwinds, 72 BPM, studying waterproof stone tablets in an underwater vault'),
        ('Great manta ray flight (II)', DUR_II[14], NEG_DRY, 'TrackType: Music, instrumental, oceanic majesty orchestral, soaring and expansive, French horns, sweeping strings, cascading harp, 75 BPM, gliding in formation with giant manta rays through blue water'),
        ('Bioluminescent night dive (II)', DUR_II[15], NEG_DRY, 'TrackType: Music, instrumental, nocturnal reef orchestral, magical and luminous, celesta, solo cello, airy synth pad, 68 BPM, diving into waters glowing with thousands of living lights'),
        ('Shipwreck reef salvage (II)', DUR_II[16], NEG_DRUMS, 'TrackType: Music, instrumental, seafaring salvage theme, industrious and bold, acoustic guitars, tambourine, violin, 80 BPM, hauling gold cannons from a shallow coral reef'),
        ('Sea temple blessing (II)', DUR_II[17], NEG_CHOIR, 'TrackType: Music, ocean temple orchestral, sacred and reverent, wordless choir harmonies, organ pad, harp, cello, 66 BPM, priests of the sea goddess blessing the expedition'),
        ('Current rider glide (II)', DUR_II[18], NEG_DRY, 'TrackType: Music, instrumental, fluid motion theme, sweeping and smooth, violin ensemble, flute runs, acoustic bass, 78 BPM, surfing warm ocean jet streams across the open sea'),
        ('Drowned kingdom promenade (II)', DUR_II[19], NEG_DRY, 'TrackType: Music, instrumental, regal aquatic march, noble and grand, brass chorale, cellos, harp glissandi, 74 BPM, walking the royal avenues of the sunken capital')
    ]
    l3_aqua = [
        ('Wrath of the sea leviathan (III)', DUR_III[0], NEG_FULL, 'TrackType: Music, oceanic battle orchestral, terrifying and massive, thundering timpani, roaring low brass, surging strings, choir roars, 120 BPM, a colossal ancient sea serpent rising from the abyss'),
        ('Kraken cataclysm (III)', DUR_III[1], NEG_FULL, 'TrackType: Music, instrumental, colossal monster attack, earth-shaking and furious, pounding taiko drums, blaring horns, frantic string ostinatos, 128 BPM, massive tentacles crushing ships and dragging them into the deep'),
        ('Tsunami tidal wave surge (III)', DUR_III[2], NEG_FULL, 'TrackType: Music, tsunami orchestral finale, overwhelming and catastrophic, sweeping full strings, crashing cymbals, thunderous brass, wordless choir, 114 BPM, a hundred-foot tidal wave crashing against fortress sea walls'),
        ('Underwater fortress siege (III)', DUR_III[3], NEG_FULL, 'TrackType: Music, instrumental, aquatic warfare orchestral, fierce and relentless, heavy war drums, driving cello runs, noble trumpet fanfares, 124 BPM, merfolk warriors and giant sharks breaching underwater gates'),
        ('Ascension of the ocean god (III)', DUR_III[4], NEG_FULL, 'TrackType: Music, ocean deity manifestation, transcendent and majestic, massive brass chorale, rolling timpani, radiant choir crescendo, full strings, 106 BPM, the god of oceans rising upon a throne of living water'),
        ('Abyssal trench eruption (III)', DUR_III[5], NEG_FULL, 'TrackType: Music, instrumental, volcanic sea cataclysm, violent and explosive, deep sub rumbles, shrieking brass blasts, rapid string arpeggios, 130 BPM, undersea volcano tearing open the seabed in blinding fire'),
        ('Merfolk army charge (III)', DUR_III[6], NEG_FULL, 'TrackType: Music, merfolk battle anthem, valiant and heroic, driving percussion, soaring horn melodies, sweeping strings, choir, 122 BPM, legions of triton knights charging into the climactic battle'),
        ('Sunken city rising (III)', DUR_III[7], NEG_FULL, 'TrackType: Music, drowned kingdom resurrection, miraculous and grand, full orchestra swells, harp cascades, triumphant brass, majestic choir, 100 BPM, the ancient sunken city breaking the surface after ten thousand years'),
        ('Great white megalodon chase (III)', DUR_III[8], NEG_FULL, 'TrackType: Music, instrumental, primeval shark hunt, relentless and terrifying, accelerating cello ostinatos, heavy bass drums, screaming brass stabs, 134 BPM, swimming for your life from a prehistoric apex predator'),
        ('Storm over the abyss (III)', DUR_III[9], NEG_FULL, 'TrackType: Music, tempest ocean battle, wild and epic, howling wind brass, crashing percussion, frantic violins, dramatic choir, 126 BPM, battling sea monsters on deck in the heart of a hurricane'),
        ('Heart of the ocean crystal (III)', DUR_III[10], NEG_FULL, 'TrackType: Music, oceanic artifact activation, radiant power, sparkling percussion, soaring trumpet themes, full strings, choir, 112 BPM, activating the pearl of tides to calm the raging seas'),
        ('Leviathan duel in the deep (III)', DUR_III[11], NEG_FULL, 'TrackType: Music, instrumental, titan monster battle, brutal and titanic, massive orchestral hits, heavy low brass, grinding cellos, 118 BPM, two gigantic sea gods clashing in the underwater abyss'),
        ('Escape from the collapsing trench (III)', DUR_III[12], NEG_FULL, 'TrackType: Music, instrumental, underwater escape momentum, breathless and fast, racing string runs, pounding drums, blaring French horns, 136 BPM, piloting the submarine out of a collapsing undersea canyon'),
        ('Triton king coronation (III)', DUR_III[13], NEG_FULL, 'TrackType: Music, aquatic royalty anthem, majestic and triumphant, royal brass fanfare, sweeping full orchestra, rolling timpani, glorious choir, 108 BPM, crowning the new emperor of the oceanic realms'),
        ('Maelstrom vortex plunge (III)', DUR_III[14], NEG_FULL, 'TrackType: Music, instrumental, giant whirlpool struggle, dizzying and fierce, spiraling string ostinatos, heavy percussion, dramatic brass, 132 BPM, caught in the center of an enormous magical ocean vortex'),
        ('Siren queen unleashed (III)', DUR_III[15], NEG_FULL, 'TrackType: Music, siren battle aria, beautiful and terrifying, soaring dramatic soprano lead, full orchestral battle, thunderous drums, 120 BPM, the siren queen commanding sea storms and shipwrecks'),
        ('Drowned temple guardian clash (III)', DUR_III[16], NEG_FULL, 'TrackType: Music, instrumental, ancient guardian duel, mighty and intense, pounding bronze percussion, roaring brass, driving strings, 124 BPM, battling four-armed stone statues in an underwater arena'),
        ('Oceanic dragon flight (III)', DUR_III[17], NEG_FULL, 'TrackType: Music, sea dragon emergence, glorious and colossal, sweeping orchestral melodies, soaring French horns, crashing cymbals, choir, 110 BPM, a majestic serpentine sea dragon bursting from the waves into the sky'),
        ('Deep sea cataclysm finale (III)', DUR_III[18], NEG_FULL, 'TrackType: Music, abyssal orchestral climax, monumental and awe-inspiring, full orchestra crescendo, thundering timpani, wordless choir peak, 102 BPM, defeating the darkness of the deep and saving the underwater realm'),
        ('Triumphant calm ocean dawn (III)', DUR_III[19], NEG_FULL, 'TrackType: Music, oceanic victory theme, radiant and peaceful, soaring French horns, warm string swells, gentle harp, triumphant choir, 104 BPM, sunlight breaking over glassy waters after the greatest sea battle')
    ]
    apply_expansion_3levels(os.path.join(base_dir, 'aqua.md'), l1_aqua, l2_aqua, l3_aqua)
    print('Expanded aqua.md')

if __name__ == '__main__':
    run_batch1('prompts/ambience')
